/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aides/': RouteRecordInfo<
      '/aides/',
      '/aides',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aides/[id]': RouteRecordInfo<
      '/aides/[id]',
      '/aides/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/AuthPage': RouteRecordInfo<
      '/AuthPage',
      '/AuthPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ForgotPassword': RouteRecordInfo<
      '/ForgotPassword',
      '/ForgotPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/cgu': RouteRecordInfo<
      '/legal/cgu',
      '/legal/cgu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/mentions': RouteRecordInfo<
      '/legal/mentions',
      '/legal/mentions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/privacy': RouteRecordInfo<
      '/legal/privacy',
      '/legal/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MesAides': RouteRecordInfo<
      '/MesAides',
      '/MesAides',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ResetPassword': RouteRecordInfo<
      '/ResetPassword',
      '/ResetPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/aides/index.vue': {
      routes:
        | '/aides/'
      views:
        | never
    }
    'src/pages/aides/[id].vue': {
      routes:
        | '/aides/[id]'
      views:
        | never
    }
    'src/pages/AuthPage.vue': {
      routes:
        | '/AuthPage'
      views:
        | never
    }
    'src/pages/ForgotPassword.vue': {
      routes:
        | '/ForgotPassword'
      views:
        | never
    }
    'src/pages/legal/cgu.vue': {
      routes:
        | '/legal/cgu'
      views:
        | never
    }
    'src/pages/legal/mentions.vue': {
      routes:
        | '/legal/mentions'
      views:
        | never
    }
    'src/pages/legal/privacy.vue': {
      routes:
        | '/legal/privacy'
      views:
        | never
    }
    'src/pages/MesAides.vue': {
      routes:
        | '/MesAides'
      views:
        | never
    }
    'src/pages/ResetPassword.vue': {
      routes:
        | '/ResetPassword'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
